exclude:     [Gemfile*, LICENSE, Rakefile, README.md]
baseurl:     /
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
markdown:    redcarpet
pygments:    true
permalink:   /blog/:year/:month/:day/:title

# Template variables
google_analytics_tracking_code: UA-26492626-1
