exclude:     [CNAME, Gemfile*, LICENSE, Rakefile, README.md]
baseurl:     /
source:      .
destination: ./_site
plugins:     ./_plugins
future:      true
markdown:    maruku
permalink:   /blog/:year/:month/:day/:title
